<a href="https://colab.research.google.com/github/sureshkumarravi/Machine_Learning/blob/master/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [12]:
#Initialization of tensors.
x =tf.constant(4)
print (x)
x =tf.constant(4.0)
print (x)
x = tf.constant(4,shape =(1,1), dtype =tf.float32)
print (x)
x = tf.constant([[1,2,3],[4,5,6]])
print(x)
x = tf.ones((3,3))
print(x)
x = tf.zeros((2,3))
print(x)
x = tf.eye(3)
print (x)
x = tf.random.normal((3,3), mean=0, stddev= 1.0)
print (x)
x = tf.random.uniform((1,3), minval= 0, maxval= 2.0)
print(x)
x = tf.range(9)
print(x)
x = tf.range(start=1, limit= 10, delta=2)
print (x)
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.08919822 -0.38293487 -1.0508325 ]
 [ 0.90355104  0.9584921   0.83677274]
 [ 1.376779    0.6645237  -2.8454533 ]], shape=(3, 3), dtype=float32)
tf.Tensor([[1.2533813  0.6942203  0.68148136]], shape=(1, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


In [24]:
#Mathematical Operations

x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
print(z)
z = x+y
print(z)
z = tf.subtract(x,y)
print(z)
z = x-y
print(z)
z = tf.divide(x,y)
print(z)
z = x/y
print(z)
z = tf.multiply(x,y)
print(z)
z = x*y
print(z)
z = tf.tensordot(x,y,axes=0)
print (z)
z = tf.reduce_sum(x*y, axis = 0)
print (z)

z = x ** 5 
print (z)

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z= x@y
print (z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[-0.6323185   2.9644115  -0.46835604  1.1652241 ]
 [-0.4145994   0.76904225  0.4716306  -0.3498451 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.6323185   2.9644115  -0.46835604  1.1652241 ]
 [-0.4145994   0.76904225  0.4716306  -0.3498451 ]], shape=(2, 4), dtype=float32)


In [28]:
#Indexing

x = tf.constant([0,1,1,2,3,4,5,6,5,4])
print (x)
print (x[:])
print (x[1:])
print (x[2:4])
print (x[::2])
print (x[::-1])

indices = tf.constant([0,3,5])
x_ind = tf.gather(x, indices)
print (x_ind)

x  = tf.constant([[0,1],
                  [2,3],
                  [4,5]])
print (x[0])
print (x[0,:])
print (x[0:2,:])




tf.Tensor([0 1 1 2 3 4 5 6 5 4], shape=(10,), dtype=int32)
tf.Tensor([0 1 1 2 3 4 5 6 5 4], shape=(10,), dtype=int32)
tf.Tensor([1 1 2 3 4 5 6 5 4], shape=(9,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 5 5], shape=(5,), dtype=int32)
tf.Tensor([4 5 6 5 4 3 2 1 1 0], shape=(10,), dtype=int32)
tf.Tensor([0 2 4], shape=(3,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)


In [41]:
#Reshaping

x = tf.range(9)
print (x)

x = tf.reshape(x, (3,3))
print (x)

x = tf.random.normal((2,3), mean = 0, stddev= 10)
print (x)

x = tf.transpose(x)
print (x)

x = tf.transpose(x, perm=[1,0])
print (x)

x = tf.constant([[[ 1,  2,  3],
                  [ 4,  5,  6]],
                 [[ 7,  8,  9],
                  [10, 11, 12]]])
print (x)

x = tf.transpose(x, perm=[2,1,0])
print (x)

x = tf.transpose(x, perm=[0,2,1])
print (x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ -4.4568334   -5.6932993   -0.45898262]
 [ 16.049297   -15.374996    -5.889089  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ -4.4568334   16.049297  ]
 [ -5.6932993  -15.374996  ]
 [ -0.45898262  -5.889089  ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ -4.4568334   -5.6932993   -0.45898262]
 [ 16.049297   -15.374996    -5.889089  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[ 1  4]
  [ 7 10]]

 [[ 2  5]
  [ 8 11]]

 [[ 3  6]
  [ 9 12]]], shape=(3, 2, 2), dtype=int32)
